"""empty message

Revision ID: 9e329b230037
Revises: 785275f80f88
Create Date: 2024-04-30 10:46:48.618893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e329b230037'
down_revision = '785275f80f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('updateDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updateDate', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
